### PR TITLE
Integration r

### PR DESCRIPTION
**Pull request by jakubczakon**
* updated r-support with the new CRAN version

### CODE REVIEW

**Comment by jakubczakon** [comment]
Can we merge it now @kamil-kaczmarek @pitercl ?

**Comment by kamil-kaczmarek** [comment]
Hey @jakubczakon @pitercl. I prefer not to. I can see some issues with recent master. I'll get back here once solved.

**Comment by jakubczakon** [comment]
ok, the reason I am asking is because this only touches the r-support file in integrations and nothing else.

**Comment by kamil-kaczmarek** [comment]
Let me take care of it @jakubczakon

**Pull request merged**
